### PR TITLE
Refresh memory in fd_fdstat_get

### LINKED ISSUE #10: Missing refreshMemory()
I was getting this error:

```
(node:17324) UnhandledPromiseRejectionWarning: TypeError: Cannot perform DataView.prototype.setUint8 on a neutered ArrayBuffer
    at DataView.setUint8 (<anonymous>)
    at /home/david/mce.new/js/node_modules/wasi/index.js:649:19
    at /home/david/mce.new/js/node_modules/wasi/index.js:427:12
    at __isatty (wasm-function[10486]:33)
    at __stdout_write (wasm-function[10487]:32)
    at __fwritex (wasm-function[10510]:171)
    at fwrite (wasm-function[10511]:16)
    at std::__2::__stdoutbuf<char>::overflow(int) (wasm-function[9355]:182)
    at std::__2::basic_streambuf<char, std::__2::char_traits<char> >::sputc(char) (wasm-function[9057]:155)
    at std::__2::ostreambuf_iterator<char, std::__2::char_traits<char> >::operator=(char) (wasm-function[9270]:131)
```

Seem to be fixed with:

```diff
diff --git a/index.js b/index.js
index e9f2e2d..dcb25bd 100644
--- a/index.js
+++ b/index.js
@@ -644,6 +644,7 @@ class WASI {
       },
       fd_fdstat_get: wrap((fd, bufPtr) => {
         const stats = CHECK_FD(fd, 0);
+        this.refreshMemory();
         this.view.setUint8(bufPtr, stats.filetype); // FILETYPE u8
         this.view.setUint16(bufPtr + 2, 0, true); // FDFLAG u16
         this.view.setUint16(bufPtr + 4, 0, true); // FDFLAG u16
```

### PR DESCRIPTION
**Pull request by davedoesdev**
Fixes #10

### CODE REVIEW

File: test/c/fd_fdstat_get_refresh.c [hunk 1]
```diff
@@ -0,0 +1,11 @@
+#include <unistd.h>
+#include <stdlib.h>
+#include <assert.h>
+
+int main(void)
+{
+    isatty(1);
+    assert(malloc(65*1024) != NULL);
```
Comment (devsnek) [inline test/c/fd_fdstat_get_refresh.c]: can you explicitly call `__builtin_wasm_memory_grow` instead?

Comment (davedoesdev) [reply test/c/fd_fdstat_get_refresh.c]: Good idea. I've done that and checked it still fails without the fix.
